### ISSUE TITLE
No documentation

### ISSUE THREAD

**Issue by maxq519** [giuliodondi/kOS-UPFG_PDI#1]
Would it be possible to get some documentation on this script?
Nothing to much, just installation and usage info.

**Comment by giuliodondi** [comment]
There is no documentation because, although the repo is public, it's still in a Work In Progress state.

I was almost done with it this summer, along with the general UPFG ascent script to go along with it. Then my attention got focussed elsewhere, namely on Shuttle scripts, and there has been a flurry of updates on the common libraries still to be integrated on this end.

I will get back to this soon

**Comment by ThePuzzlemaker** [comment]
@giuliodondi What is the status of this?

**Comment by giuliodondi** [comment]
I haven't done any work on this repository since the issue was first opened. I got sidetracked with mroe Shuttle developments. 
I will get back on this, I promise
